version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12-browsers

commands:
  npm_install:
    description: 'Install Dependencies'
    steps:
      - run: npm install
      - save_cache:
          key: node-cache-node12-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  restore_npm_cache:
    description: 'Restore Cached Dependencies'
    steps:
      - restore_cache:
          keys:
            - node-cache-node12-{{ checksum "package-lock.json" }}
            - node-cache-node12-
  setup:
    description: 'Setup Executor'
    steps:
      - checkout
      - restore_npm_cache
      - npm_install

jobs:
  build-master:
    executor: default
    steps:
      - setup
      - run: npx nx affected --target=lint --base=origin/master~1 --parallel
      - run: npx nx affected --target=test --base=origin/master~1
      - run: npx nx affected --target=build --base=origin/master~1
  build-pr:
    executor: default
    steps:
      - setup
      - run: npx nx affected --target=lint --base=origin/master --parallel
      - run: npx nx affected --target=test --base=origin/master
      - run: npx nx affected --target=build --base=origin/master

workflows:
  version: 2.1
  default_workflow:
    jobs:
      - build-master:
          filters:
            branches:
              only:
                - master
      - build-pr:
          filters:
            branches:
              ignore:
                - master
