name: PR on master

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
    - master
    types: [opened, reopened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install environment
      run: npm install
        
    - name: Linter
      run: npm run affected:lint
    
    - name: Unit / Integration Tests
      run: npm run affected:test

    - name: E2E Tests
      run: npm run affected:apps
